# Generated by Django 4.0.6 on 2022-08-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='space_slug',
            field=models.SlugField(default='space-unassigned'),
            preserve_default=False,
        ),
    ]
