# Generated by Django 4.0.6 on 2022-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_slug_post_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='space_slug',
            field=models.CharField(max_length=100),
        ),
    ]
