# Generated by Django 4.0.6 on 2022-08-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_space_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='space_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
