# Generated by Django 4.0.6 on 2022-08-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_post_slug_alter_post_space_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='space_slug',
            new_name='spaceslug',
        ),
    ]
