# Generated by Django 4.0.6 on 2022-08-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_space_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='slug',
            field=models.SlugField(default='old-name'),
        ),
    ]
