# Generated by Django 4.0.6 on 2022-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_alter_space_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
