# Generated by Django 4.0.6 on 2022-08-08 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_alter_space_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='id',
        ),
        migrations.AlterField(
            model_name='space',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
