# Generated by Django 4.0.6 on 2022-08-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_remove_space_id_alter_space_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
