# Generated by Django 4.0.6 on 2022-08-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0008_rename_slug_space_spaceslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='spaceslug',
            new_name='slug',
        ),
    ]
